name: Tracks

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["*"]

jobs:
  list-track:
    name: List track ${{ matrix.track }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        track:
          - elastic/endpoint
          - elastic/logs
          - elastic/security

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: python3 -m pip install "https://github.com/elastic/rally/archive/master.tar.gz"

      - name: List track
        run: esrally list tracks --track-path=${{ matrix.track }}

  it:
    name: integration tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: python3 -m pip install "https://github.com/elastic/rally/archive/master.tar.gz"
        run: python3 -m pip install "pytest==6.2.5"
        run: python3 -m pip install "https://github.com/elastic/pytest-rally/archive/master.tar.gz"

      - name: Run integration tests
        run: |
          pytest it/ --log-cli-level=INFO
